spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    alicloud:
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
      access-key: LTAI5tLwVAaQxcqnpURffyY4
      secret-key: QKqCKX3N6FueNcvZrvID4cfP5gHvyb
  application:
    name: cubemall-third-party
server:
  port: 30000